genres = [
	{"id": 2, "genreName": "Blues"},
	{"id": 3, "genreName": "Comedy"},
	{"id": 4, "genreName": "Children's Music"},
	{"id": 5, "genreName": "Classical"},
	{"id": 6, "genreName": "Country"},
	{"id": 7, "genreName": "Electronic"},
	{"id": 8, "genreName": "Holiday"},
	{"id": 9, "genreName": "Opera"},
	{"id": 11, "genreName": "Jazz"},
	{"id": 12, "genreName": "Latino"},
	{"id": 13, "genreName": "New Age"},
	{"id": 14, "genreName": "Pop"},
	{"id": 15, "genreName": "R&B/Soul"},
	{"id": 16, "genreName": "Soundtrack"},
	{"id": 17, "genreName": "Dance"},
	{"id": 18, "genreName": "Hip-Hop/Rap"},
	{"id": 19, "genreName": "World"},
	{"id": 20, "genreName": "Alternative"},
	{"id": 21, "genreName": "Rock"},
	{"id": 22, "genreName": "Christian&Gospel"},
	{"id": 23, "genreName": "Vocal"},
	{"id": 24, "genreName": "Reggae"},
	{"id": 25, "genreName": "Easy Listening"},
	{"id": 27, "genreName": "J-Pop"},
	{"id": 28, "genreName": "Enka"},
	{"id": 29, "genreName": "Anime"},
	{"id": 30, "genreName": "Kayokyoku"},
	{"id": 50, "genreName": "Fitness&Workout"},
	{"id": 51, "genreName": "K-Pop"},
	{"id": 52, "genreName": "Karaoke"},
	{"id": 53, "genreName": "Instrumental"}
]

def GetMusicGenres():
	return genres